breaks build
$ fab
[localhost] local: rm -fr .output/*
[localhost] local: pelican --settings settings.py
CRITICAL:
'/home/tshepang/projects/blog/.output/theme/css/pygments.css' does not
exist

Fatal error: local() encountered an error (return code 1) while
executing 'pelican --settings settings.py'

Aborting.